const $=s=>document.querySelector(s),today=new Date(),iso=d=>d.toISOString().slice(0,10),offset=n=>{let d=new Date();d.setDate(d.getDate()+n);return iso(d)};
let tasks=[
 {id:1,title:'Finalizar apresentação para o cliente',description:'Revisar os slides e adicionar os dados de desempenho.',project:'Trabalho',priority:'high',date:offset(0),tag:'Design',done:false},
 {id:2,title:'Reunião de alinhamento semanal',description:'Definir prioridades e próximos passos com o time.',project:'Trabalho',priority:'medium',date:offset(0),tag:'Reunião',done:false},
 {id:3,title:'Responder e-mails pendentes',description:'',project:'Trabalho',priority:'low',date:offset(0),tag:'',done:false},
 {id:4,title:'Comprar ingredientes para o jantar',description:'Passar no mercado depois do trabalho.',project:'Pessoal',priority:'medium',date:offset(0),tag:'Casa',done:false},
 {id:5,title:'Organizar referências do projeto',description:'',project:'Estudos',priority:'low',date:offset(-1),tag:'Pesquisa',done:true},
 {id:6,title:'Revisar planejamento mensal',description:'',project:'Pessoal',priority:'medium',date:offset(2),tag:'',done:false}
], projects=[{name:'Trabalho',color:'#6d5dfc'},{name:'Pessoal',color:'#ec8c6c'},{name:'Estudos',color:'#50b9a4'}], activeView='today',editingId=null,filters={priority:'all',project:'all'};
const esc=t=>{let e=document.createElement('div');e.textContent=t;return e.innerHTML}, day=iso(today);
function formatDate(date){let n=Math.round((new Date(date+'T12:00')-new Date(day+'T12:00'))/864e5);if(n===0)return'Hoje';if(n===1)return'Amanhã';if(n===-1)return'Ontem';return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(date+'T12:00')).replace('.','')}
function visible(){let q=$('#search-input').value.trim().toLowerCase();return tasks.filter(t=>{let v=activeView==='today'?t.date===day&&!t.done:activeView==='upcoming'?t.date>day&&!t.done:activeView==='completed'?t.done:true;return v&&(filters.priority==='all'||t.priority===filters.priority)&&(filters.project==='all'||t.project===filters.project)&&(!q||`${t.title} ${t.description} ${t.project} ${t.tag}`.toLowerCase().includes(q))}).sort((a,b)=>+a.done-+b.done||a.date.localeCompare(b.date))}
function renderProjects(){ $('#projects-list').innerHTML=projects.map(p=>`<button class="project-button" data-project="${p.name}"><i class="project-dot" style="background:${p.color}"></i>${p.name}<small>${tasks.filter(t=>t.project===p.name&&!t.done).length}</small></button>`).join('');let opt=projects.map(p=>`<option value="${p.name}">${p.name}</option>`).join('');$('#task-project').innerHTML=opt;$('#project-filter').innerHTML='<option value="all">Todos os projetos</option>'+opt }
function dashboard(){let open=tasks.filter(t=>!t.done),done=tasks.filter(t=>t.done).length,p=tasks.length?Math.round(done/tasks.length*100):0;$('#today-count').textContent=open.filter(t=>t.date===day).length;$('#upcoming-count').textContent=open.filter(t=>t.date>day).length;$('#completed-week').textContent=done;$('#weekly-total').textContent=tasks.length;$('#weekly-progress').textContent=p+'%';$('#progress-bar').style.width=p+'%';let f=tasks.find(t=>!t.done&&t.priority==='high'&&t.date===day)||open[0];$('#focus-card').hidden=!f;if(f){$('#focus-title').textContent=f.title;$('#focus-detail').textContent=`${f.project} · ${formatDate(f.date)}`;$('#focus-complete').dataset.id=f.id}let l={today:['Bom dia, Pedro','Você tem tarefas esperando por você.'],upcoming:['Próximas tarefas','Planeje seus próximos dias com calma.'],all:['Todas as tarefas','Uma visão geral de tudo o que precisa acontecer.'],completed:['Tarefas concluídas','Celebre o que você já realizou.']}[activeView];$('#page-title').innerHTML=l[0]+(activeView==='today'?' <span>☀</span>':'');$('#page-subtitle').textContent=l[1];$('#today-label').textContent=activeView==='today'?new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(today):''}
function render(){let list=visible();$('#tasks-list').innerHTML=list.map(t=>`<article class="task ${t.done?'done':''}" data-id="${t.id}"><input class="task-check" type="checkbox" ${t.done?'checked':''}><i class="priority-line priority-${t.priority}"></i><div class="task-main"><div class="task-name">${esc(t.title)}</div>${t.description?`<div class="task-description">${esc(t.description)}</div>`:''}</div><div class="task-meta">${t.tag?`<span class="task-tag">${esc(t.tag)}</span>`:''}<span class="task-date ${t.date<day&&!t.done?'overdue':''}">◷ ${formatDate(t.date)}</span><button class="task-menu">•••</button></div></article>`).join('');$('#empty-state').hidden=!!list.length;$('#task-summary').textContent=`${list.length} ${list.length===1?'tarefa':'tarefas'}`;dashboard()}
function modal(t){editingId=t?.id||null;$('#modal-title').textContent=t?'Editar tarefa':'Nova tarefa';$('.save-button').textContent=t?'Salvar alterações':'Criar tarefa';$('#task-title').value=t?.title||'';$('#task-description').value=t?.description||'';$('#task-project').value=t?.project||projects[0].name;$('#task-priority').value=t?.priority||'medium';$('#task-date').value=t?.date||day;$('#task-tag').value=t?.tag||'';$('#modal-backdrop').hidden=false;setTimeout(()=>$('#task-title').focus(),50)}
function close(){ $('#modal-backdrop').hidden=true;$('#task-form').reset();editingId=null }function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
document.addEventListener('click',e=>{let n=e.target.closest('[data-view]'),p=e.target.closest('[data-project]'),task=e.target.closest('.task');if(n){activeView=n.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===n));render()}if(p){activeView='all';filters.project=p.dataset.project;$('#project-filter').value=filters.project;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='all'));render()}if(e.target.closest('#open-task-modal,[data-open-modal]'))modal();if(e.target.closest('.close-modal,.cancel-button')||e.target===$('#modal-backdrop'))close();if(task&&e.target.matches('.task-check')){let t=tasks.find(x=>x.id==task.dataset.id);t.done=e.target.checked;toast(t.done?'Tarefa concluída. Muito bem!':'Tarefa reaberta.');render()}if(task&&e.target.closest('.task-menu'))modal(tasks.find(x=>x.id==task.dataset.id));if(e.target.closest('#focus-complete')){tasks.find(x=>x.id==e.target.closest('#focus-complete').dataset.id).done=true;toast('Foco do dia concluído!');render()}if(e.target.closest('#filter-toggle'))$('#filter-panel').hidden=!$('#filter-panel').hidden;if(e.target.closest('#clear-filters')){filters={priority:'all',project:'all'};$('#priority-filter').value='all';$('#project-filter').value='all';render()}if(e.target.closest('#theme-toggle')){document.body.classList.toggle('dark');$('#theme-toggle').textContent=document.body.classList.contains('dark')?'☀':'☾'}if(e.target.closest('#mobile-menu'))$('#sidebar').classList.toggle('open');if(e.target.closest('#add-project')){let name=prompt('Nome do novo projeto:');if(name?.trim()&&!projects.some(x=>x.name.toLowerCase()===name.trim().toLowerCase())){projects.push({name:name.trim(),color:'#8e82ef'});renderProjects();toast('Projeto criado.')}}});
$('#task-form').addEventListener('submit',e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target));if(editingId)Object.assign(tasks.find(x=>x.id===editingId),v);else tasks.unshift({...v,id:Date.now(),done:false});toast(editingId?'Tarefa atualizada.':'Nova tarefa criada.');close();renderProjects();render()});$('#search-input').addEventListener('input',render);$('#priority-filter').addEventListener('change',e=>{filters.priority=e.target.value;render()});$('#project-filter').addEventListener('change',e=>{filters.project=e.target.value;render()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search-input').focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();modal()}if(e.key==='Escape')close()});renderProjects();render();
